spring.application.name=JavaPractice
spring.output.ansi.enabled=true

#H2-database configuration
# H2 Database config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# To enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# To auto-create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#debug=true
server.port=8081